mv /home/dataset-assist-0/luojy/models/Wan2.1-I2V-14B-720P-Diffusers    /home/dataset-assist-0/public-models/Wan2.1-I2V-14B-720P-Diffusers
mv /home/dataset-assist-0/luojy/models/Wan2.1-T2V-14B-Diffusers         /home/dataset-assist-0/public-models/Wan2.1-T2V-14B-Diffusers
mv /home/dataset-assist-0/luojy/models/HunyuanVideo                     /home/dataset-assist-0/public-models/HunyuanVideo
mv /home/dataset-assist-0/luojy/models/HunyuanVideo-I2V                 /home/dataset-assist-0/public-models/HunyuanVideo-I2V
mv /home/dataset-assist-0/luojy/models/Wan2.1-VACE-14B-diffusers        /home/dataset-assist-0/public-models/Wan2.1-VACE-14B-diffusers
mv /home/dataset-assist-0/luojy/models/Wan2.2-I2V-A14B-Diffusers        /home/dataset-assist-0/public-models/Wan2.2-I2V-A14B-Diffusers
mv /home/dataset-assist-0/luojy/models/Wan2.2-Animate-14B-Diffusers     /home/dataset-assist-0/public-models/Wan2.2-Animate-14B-Diffusers
mv /home/dataset-assist-0/luojy/models/Wan2.1-VACE-1.3B-diffusers       /home/dataset-assist-0/public-models/Wan2.1-VACE-1.3B-diffusers
mv /home/dataset-assist-0/luojy/models/Wan2.1-T2V-1.3B-Diffusers        /home/dataset-assist-0/public-models/Wan2.1-T2V-1.3B-Diffusers
mv /home/dataset-assist-0/luojy/models/skyreels-v2-i2v-14b              /home/dataset-assist-0/public-models/skyreels-v2-i2v-14b
mv /home/dataset-assist-0/luojy/models/skyreels-v2-t2v-14b              /home/dataset-assist-0/public-models/skyreels-v2-t2v-14b
mv /home/dataset-assist-0/luojy/models/mochi-1                          /home/dataset-assist-0/public-models/mochi-1
mv /home/dataset-assist-0/luojy/models/easyanimate-v5-t2v-12b           /home/dataset-assist-0/public-models/easyanimate-v5-t2v-12b
mv /home/dataset-assist-0/luojy/models/CogVideoX-5b                     /home/dataset-assist-0/public-models/CogVideoX-5b
mv /home/dataset-assist-0/luojy/models/CogVideoX-5b-I2V                 /home/dataset-assist-0/public-models/CogVideoX-5b-I2V
mv /home/dataset-assist-0/luojy/models/Self-Forcing                     /home/dataset-assist-0/public-models/Self-Forcing
mv /home/dataset-assist-0/luojy/models/Causal-Forcing                   /home/dataset-assist-0/public-models/Causal-Forcing
mv /home/dataset-assist-0/luojy/models/Reward-Forcing                   /home/dataset-assist-0/public-models/Reward-Forcing
mv /home/dataset-assist-0/luojy/models/Rolling-Forcing                  /home/dataset-assist-0/public-models/Rolling-Forcing
mv /home/dataset-assist-0/luojy/models/VBench-models                    /home/dataset-assist-0/public-models/VBench-models