# Supported methods (10):
# dense, svg1, svg2, spargeattn, radial, sta, draft, adacluster, flashomni, svoo
#
# Supported backbones (19):
# wan1.3b, wan14b, wan22, hunyuan, wan14b-i2v, wan22-i2v, hunyuan-i2v,
# skyreels-v2, skyreels-v2-i2v, wananimate, wan-vace, wan21-vace-14b,
# cogvideox, cogvideox-i2v, ltx, ltx-i2v, allegro, mochi, easyanimate
#
# Total command lines: 190 = 19 backbones x 10 methods.
# Image/video-conditioned commands use repo-local test_inputs/ assets:
# I2V uses test_inputs/portrait.jpg, WanAnimate uses the aligned character/
# pose/face inputs, and WanVACE uses the paired reference/mask videos.

export SPARSEVIDEO_MODEL_ROOT=${SPARSEVIDEO_MODEL_ROOT:-/home/dataset-assist-0/public-models}

CUDA_VISIBLE_DEVICES=0 python scripts/infer.py --model wan1.3b --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' # 12:08
CUDA_VISIBLE_DEVICES=1 python scripts/infer.py --model wan1.3b --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'  # 07:29
CUDA_VISIBLE_DEVICES=2 python scripts/infer.py --model wan1.3b --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'  # 06:56
CUDA_VISIBLE_DEVICES=3 python scripts/infer.py --model wan1.3b --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' # 08:14
CUDA_VISIBLE_DEVICES=0 python scripts/infer.py --model wan1.3b --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' # 07:22
CUDA_VISIBLE_DEVICES=1 python scripts/infer.py --model wan1.3b --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' # 
python scripts/infer.py --model wan1.3b --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan1.3b --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan1.3b --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wan1.3b --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --profile upstream
python scripts/infer.py --model wan14b --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wan14b --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan22 --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wan22 --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model hunyuan --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model hunyuan --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model hunyuan --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model hunyuan --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config mode=full --method-config value=null
python scripts/infer.py --model hunyuan --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model hunyuan --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --profile upstream
python scripts/infer.py --model hunyuan --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model hunyuan --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model hunyuan --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu --method-config D=1 --cpu-offload --cpu-offload-mode model --vae-tiling --vae-slicing --vae-decoder-chunk-size 1
python scripts/infer.py --model hunyuan --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model wan14b-i2v --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan14b-i2v --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wan14b-i2v --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wan22-i2v --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model wan22-i2v --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wan22-i2v --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model hunyuan-i2v --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model hunyuan-i2v --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model hunyuan-i2v --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model hunyuan-i2v --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --method-config mode=full --method-config value=null
python scripts/infer.py --model hunyuan-i2v --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model hunyuan-i2v --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model hunyuan-i2v --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model hunyuan-i2v --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model hunyuan-i2v --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu --method-config D=1 --cpu-offload --cpu-offload-mode model --vae-tiling --vae-slicing --vae-decoder-chunk-size 1
python scripts/infer.py --model hunyuan-i2v --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2 --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2 --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model skyreels-v2 --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model skyreels-v2-i2v --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model skyreels-v2-i2v --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model skyreels-v2-i2v --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg
python scripts/infer.py --model wananimate --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wananimate --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4 --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wananimate --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/character.jpg --pose-video test_inputs/pose_video.mp4 --face-video test_inputs/face_video.mp4
python scripts/infer.py --model wan-vace --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan-vace --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4 --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wan-vace --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model wan21-vace-14b --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4 --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model wan21-vace-14b --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --reference-video test_inputs/video_ref.mp4 --mask-video test_inputs/video_mask.mp4
python scripts/infer.py --model cogvideox --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --cpu-offload --cpu-offload-mode model
python scripts/infer.py --model cogvideox --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model cogvideox --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model cogvideox-i2v --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model cogvideox-i2v --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720 --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model cogvideox-i2v --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 480 --width 720
python scripts/infer.py --model ltx --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280 --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model ltx --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model ltx-i2v --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280 --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model ltx-i2v --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --image test_inputs/portrait.jpg --height 704 --width 1280
python scripts/infer.py --model allegro --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=0 python scripts/infer.py --model allegro --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=1 python scripts/infer.py --model allegro --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=2 python scripts/infer.py --model allegro --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=3 python scripts/infer.py --model allegro --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=0 python scripts/infer.py --model allegro --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=1 python scripts/infer.py --model allegro --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=2 python scripts/infer.py --model allegro --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
CUDA_VISIBLE_DEVICES=3 python scripts/infer.py --model allegro --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
CUDA_VISIBLE_DEVICES=0 python scripts/infer.py --model allegro --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --vae-tiling
python scripts/infer.py --model mochi --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model mochi --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
CUDA_VISIBLE_DEVICES=0 python scripts/infer.py --model mochi --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model mochi --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model mochi --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model mochi --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model mochi --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model mochi --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model mochi --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model mochi --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method dense --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method svg1 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method svg2 --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method spargeattn --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method radial --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method sta --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method draft --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method adacluster --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
python scripts/infer.py --model easyanimate --method flashomni --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic' --method-config sparse_pattern=paper_mmdit --method-config use_sparse_gemm=false --method-config taylor_cache_device=cpu
python scripts/infer.py --model easyanimate --method svoo --prompt 'A cinematic shot of a red sports car driving along a coastal road at sunset, detailed, realistic'
